---
title: "Serg's Project Working File"
author: "Sergio Ozoria"
date: "2025-11-26"
output: github_document
---

# 1. Preparing variables

```{r loading package}
library(tidyverse)
```


```{r}
#  serg - cleaning up name using snake format + concatenating missing values 
poke_tidy = read_csv("./Data/pokemon.csv", na = c("NA", ".", "")) |> 
  janitor::clean_names()

# serg - replacing missing type 2 with none
poke_tidy = poke_tidy |> 
  mutate(
    type2 = ifelse(is.na(type2), "None", type2),
    type1 = str_to_title(type1),
    type2 = str_to_title(type2)
  ) |> 
  distinct(name, .keep_all = TRUE)

# serg - cleaning up abilities (could also create variables for each)
poke_tidy = poke_tidy |> 
  mutate(
    abilities = str_remove_all(abilities, "\\[|\\]|'")
  )

# serg - in case there's missing gender 
poke_tidy = poke_tidy |> 
  mutate(
    genderless = ifelse(is.na(percentage_male), TRUE, FALSE)
  )

# serg - categorical var for plotting/modeling
poke_tidy = poke_tidy |> 
  mutate(
    type1 = factor(type1),
    type2 = factor(type2),
    generation = factor(generation),
    is_legendary = as.logical(is_legendary)
  )
```


```{r}
# eman - convert  numeric columns

poke_tidy=
  poke_tidy |> 
  mutate(across(
    .cols = c(starts_with("against_"), "hp", "attack", "defense", "sp_attack", "sp_defense", "speed", "height_m", "weight_kg", "base_total"),
    .fns = as.numeric
  )) 

```

```{r}
# eman - create total stats

poke_tidy =
  poke_tidy |> 
  mutate(total_stats = hp + attack +defense + sp_attack + sp_defense + speed )
```

```{r}
# eman - create attack/defense ratio (useful for visuals later)

poke_tidy = 
  poke_tidy |> 
  mutate(offense_defense_ratio = attack / defense)
```

```{r}
# eman - starting with basic eda

head(poke_tidy)

ggplot(poke_tidy, aes(total_stats))+
  geom_histogram(bins = 30, fill = "skyblue", color = "black")+
  labs(title = "Distribution of Total Stats")
```

```{r}
# eman - average total stats by type

ggplot(poke_tidy, aes(type1, total_stats))+
  geom_boxplot()+
  coord_flip()+
  labs(title = "Total Stats by Primary Type")
```

```{r}
#eman - height vs weight colored by strength

ggplot(poke_tidy, aes(height_m, weight_kg, color = total_stats))+
  geom_point(alpha = 0.6, size =2)+
  scale_color_viridis_c()+
  labs(title = "Height vs Weight (Colored by total stats")
```

```{r}
# eman - hypothesis testing
# test 1: ANOVA - Do types differ in strength?
# Null hypothesis: mean total stats are equal across all types

anova_type = 
  aov(total_stats ~ type1, data = poke_tidy)
summary(anova_type)
```


```{r}
# eman - hypothesis testing
# test 2: t-test - Are legendary Pokemon stronger?
# Null hypothesis:legendary and non-legendary pokemon have the same mean total stats

t.test(total_stats ~ is_legendary, data = poke_tidy)
```

```{r}
# eman - logistic regression (predicting legendary)

legend_model =
  glm (
    is_legendary ~ total_stats + type1+ generation,
    data = poke_tidy, 
    family = "binomial"
  )
summary(legend_model)

poke_tidy$predicted_legendary =
  predict(legend_model, type = "response")

```

```{r}
#eman - saving clean dataset

write_csv(poke_tidy, "Data/pokemon_clean.csv")
```










